AllCops:
  DisplayCopNames: true
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
  Exclude:
    - 'config/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'spec/spec_helper.rb'
    - Gemfile
    - Rakefile
    - rubocop_pre_commit_hook.rb
  
Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false
